# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-umEs2dsHyTDAUnBbHLr1oxq8te4dB0t
"""

import random 
import numpy as np
import pandas as pd
import sklearn
from sklearn import tree
from scipy import stats
random.seed(42)  # don't change this line

# Load all data tables
df1 = pd.read_csv('/content/2017_18_master.csv')
df2 = pd.read_csv('/content/2018_19_master.csv')
df3 = pd.read_csv('/content/2019_20_master.csv')
df4 = pd.read_csv('/content/2020_21_master.csv')

df5 = pd.read_csv('/content/2018_19_ucl.csv')
df6 = pd.read_csv('/content/2019_20_ucl.csv')
df7 = pd.read_csv('/content/2020_21_ucl.csv')

df8 = pd.read_csv('/content/2018_19_uel.csv')
df9 = pd.read_csv('/content/2019_20_uel.csv')
df10 = pd.read_csv('/content/2020_21_uel.csv')

df4.head()

df = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10]).drop_duplicates()

df.head()

my_list = df.columns.values.tolist()
for item in my_list:
  print("\'" + item + "\',")

df_temp = df[['Player', 'Nation', 'Born', 'Season', 'Squad', 'Comp',
'yellow_cards',
'red_cards',
'2nd_yellow_cards',
'fouls_committed',
'fouls_drawn',
'offsides',
'pks_won',
'pks_conceded',
'own_goals',
'loose_balls_recovered',
'aerials_won',
'aerials_lost',
'aerials_won_pct'
]]
df_temp.head()

df_temp = df_temp.drop_duplicates()
df_temp.to_csv(path_or_buf='/content/player_misc_master.csv', index=False)